BookBazaar/Controllers/AdminController.cs
using Data.Entities;
using Data.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BookBazaar.Controllers;

public class AdminController : Controller
{
    IBookRepository _bookRepository;
    private readonly IOrderRepository _orderRepository;
    private readonly IOrderedBookRepository _orderedBookRepository;

    public AdminController(IBookRepository bookRepository, IOrderRepository orderRepository, IOrderedBookRepository orderedBookRepository)
    {
        _bookRepository = bookRepository;
        _orderRepository = orderRepository;
        _orderedBookRepository = orderedBookRepository;
    }

    public ActionResult Index()
    {
        return RedirectToAction("BookList");
    }

    public ViewResult BookList()
    {
        return View(_bookRepository.GetBook);
    }

    public ViewResult OrderList()
    {
        return View(_orderRepository.GetOrders);
    }

    public ViewResult OrderedBookList(Guid id)
    {
        var orderedBook = _orderedBookRepository.GetOrderedBook.Where(p => p.OrderId == id).ToList();
        return View(orderedBook);
    }

    public ViewResult Add()
    {
        return View(new Book());
    }

    [HttpPost]
    public ActionResult Add(Book book)
    {
        if (ModelState.IsValid)
        {
            _bookRepository.Add(book);
            TempData["message"] = string.Format($"Товар \"{book.Name}\" збережено");
            return RedirectToAction("BookList");
        }
        else
        {
            return View(book);
        }
    }

    public ViewResult Edit(Guid id)
    {
        Book book = _bookRepository.GetBook.FirstOrDefault(p => p.Id == id);
        return View(book);
    }

    [HttpPost]
    public ActionResult Edit(Book book)
    {
        if (ModelState.IsValid)
        {
            _bookRepository.Update(book);
            TempData["message"] = string.Format($"Зміни інформації про товар \"{book.Name}\" збережено");
            return RedirectToAction("BookList");
        }
        else
        {
            return View(book);
        }
    }

    [HttpPost]
    public ActionResult Delete(Book book)
    {
        _bookRepository.Delete(book.Id);
        return RedirectToAction("BookList");
    }
}

BookBazaar/Controllers/NavController.cs
using Data.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BookBazaar.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repository)
        {
            this.repository = repository;
        }
        public PartialViewResult Menu(string genre)
        {
            ViewBag.SelectedCategory = genre;

            IEnumerable<string> genres = repository.GetBook
                .Select(p => p.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(genres);
        }
    }
}

BookBazaar/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Панель Адміністратора</a>
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-2">
            @Html.ActionLink("Список книг", "BookList", "Admin", null, new { @class = "btn btn-block btn-default btn-lg" })
            @Html.ActionLink("Список заказів", "OrderList", "Admin", null, new { @class = "btn btn-block btn-default btn-lg" })
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>

BookBazaar/Views/Shared/_BookSummary.cshtml
@model Data.Entities.Book

<div class="well">
    <div class="row">
        <div class="col-xs-10">
            <h3>
                <strong>@Model.Name</strong>
            </h3>
        </div>
        <div class="col-xs-2">
            <h3>
                <strong id="price" class="pull-right label label-primary">
                    @Model.Price.ToString("#.## грн")
                </strong>
            </h3>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor( x=> x.Id)
                    @Html.Hidden("returnUrl", Context.Request.Path)
                    <input type="submit" class="btn btn-success" value="Додати до кошика" />
                </div>
            }
        </div>
    </div>
    <span class="lead">@Model.Description</span>
</div>

BookBazaar/Views/Shared/_Layout.cshtml
@using BookBazaar.HtmlHelper
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Замовлення книжки додому</a>
        @Html.RenderAction("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.RenderAction("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>